### ISSUE TITLE
Memory Consistency Issue in L2

### ISSUE THREAD

**Issue by zhemao** [ucb-bar/uncore#18] opened 2016-03-05 00:56 UTC
Detected with AXE tracegen tool and random seed 8285.

    make CONFIG=TraceGenConfig debug
    ./emulator-Top-TraceGenConfig-debug -s8285 +verbose 2>&1 | toaxe.py - | axe-shrink.py WMO -

    # &M[3] == 0x0000000010
    # &M[1] == 0x0000000008
    # &M[0] == 0x0000000108
    # &M[2] == 0x0000100008

    0: M[1] := 4 @ 65:
    0: M[1] := 22 @ 283:
    1: M[1] == 22 @ 64:105
    1: M[1] == 4 @ 191:311

Bad meta write at CPU 0 cycle count 332 (decimal).

**Comment by zhemao** [comment] 2016-03-05 00:58
VCD at /nscratch/zhemao/consistency-bug.vcd

**Comment by hcook** [comment] 2016-03-05 01:52
This issue is caused by a race between a VoluntaryReleaseTracker handling a L1 writeback and an AcquireTracker handing an AcquireShared (the first read) on the same line. The AcquireTracker doesn't know about the writeback; its Probe of the L1 returns a releaseDowngradeAck, so while it returns the correct answer for the read, the metadata it writes to the L2 records both cores as sharers and sets the outer state to cleanExclusive. This results in the block being silently dropped upon eviction (why?). The second read misses in both caches and reads stale data from memory.

**Comment by aswaterman** [comment] 2016-03-05 02:37
Isn't having two trackers manipulate the same line a recipe for disaster?
It's hard to imagine how to cover all possible interactions.

In the case of the voluntary release tracker being allocated first, the
acquire should just block until the release is complete.  The other case is
obviously harder because not handling the voluntary release will cause
deadlock.  Maybe in that case the release should be merged into the
outstanding acquire tracker somehow, rather than allocating a second one.

**Comment by hcook** [comment] 2016-03-05 02:54
I think the first case is never a problem because the worst that can happen is an extra probe message is sent, at least with the existing protocols. That said, it's not hard guard to add, so probably best to go ahead with it.

The second (which is being exhibited here) is harder. I'm evaluating whether it's better to actually take on handling the whole voluntary release (which needs to be merged and acked) in the AcquireTracker, versus just snooping its data (which is what the writeback unit does now) up to a certain point in the transaction and then blocking them once forward progress is guaranteed.

**Comment by kenmcmil** [comment] 2016-03-07 20:08
It looks like issue 18 and 20 are symptoms of the same problem. That is, the Acquire tracker needs to take a lock on the metadata between reading and writing, but this creates a priority inversion with respect to the Release tracker. Maybe a simple way to handle this would be to have the Release tracker set a flag in the Acquire tracker indicating the metadata may have changed. This would cause the Acquire tracker to restart after collecting the involuntary Releases but before Grant. When you start doing Grants, you block involuntary releases.

**Comment by kenmcmil** [comment] 2016-03-07 21:26
[dump.txt](https://github.com/ucb-bar/uncore/files/162101/dump.txt)

Above VCD file shows the issue in the randomized unit tester (change the extension from .txt to .vcd). You can see in this sequence that when the voluntary release arrives before the Acquire, we still have a problem. That is, it is not just an unneeded probe -- the coherence state is corrupted.

172 ps: Voluntary Release (dirty) of cache line 0 by client 0

176 ps: Acquire of cache line 0 by client 1

184 ps: Probe of cache line 0, client 0

188 ps: Ack of voluntary Release

196 ps: Involuntary release (clean) of cache line 0 by client 0

208 ps: Grant of cache line 0 to client 1

216 ps: Finish from client 1

220 ps: Wrong outer state (ExclusiveShared) written to cache line 0 tag.

**Closed** 2016-03-11 01:15 UTC
